config/urls.py
from django.contrib import admin
from django.urls import path, include
import todo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.TaskView.as_view(), name='todo'),
    path('delete/<int:pk>', views.DeleteTaskView.as_view(), name='delete'),
    path('done/<int:pk>', views.DoneTaskView.as_view(), name='done'),
    path('filter/<str:filter>', views.TaskView.as_view(), name='filter'),
]

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Task(models.Model):
    is_done = models.BooleanField(default=False)
    details = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    archive = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.details}'

    class Meta:
        ordering = ['-created_at']

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView
from todo.models import Task


class TaskView(CreateView):
    model = Task
    fields = ['details', 'owner']
    template_name = 'todo/todo.html'
    success_url = reverse_lazy('todo:todo')

    def get_context_data(self, **kwargs):
        filter_ = self.kwargs.get('filter', None)
        context = super().get_context_data(**kwargs)
        if filter_ is None or filter == 'ongoing':
            context['task_list'] = Task.objects.filter(is_done=False, archive=False)
        elif filter_ == 'all':
            context['task_list'] = Task.objects.filter(archive=False)
        elif filter_ == 'done':
            context['task_list'] = Task.objects.filter(is_done=True, archive=False)
        return context


class DeleteTaskView(View):
    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        task.archive = True
        task.save()
        return HttpResponseRedirect(reverse('todo:todo'))


class DoneTaskView(View):
    def post(self, request, pk):
        task = Task.objects.get(pk=pk)
        task.is_done = True
        task.save()
        return HttpResponseRedirect(reverse('todo:todo'))

todo/templates/todo/todo.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>To Do list</title>
</head>
<body>
    <h1>To Do list</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>

    <br>

    <form action="{% url 'todo:filter' 'all' %}" method="post">
        {% csrf_token %}
        <button>show all</button>
    </form>

    <form action="{% url 'todo:filter' 'done' %}" method="post">
        {% csrf_token %}
        <button>show done</button>
    </form>

    <form action="{% url 'todo:filter' 'ongoing' %}" method="post">
        {% csrf_token %}
        <button>show ongoing</button>
    </form>

    <h2>Ongoing tasks</h2>

    <ul>
        {% for task in task_list %}
             <li>
                 {{ task }}
                 <br>
                 <a href="{% url 'todo:delete' task.pk %}">Delete task</a>
                 <form action="{% url 'todo:done' task.pk %}" method="post">
                     {% csrf_token %}
                     <button type="submit">Task done</button>
                 </form>
             </li>
        {% endfor %}
    </ul>
</body>
</html>